# Checks for new upstream releases and creates matching local releases

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      # Get the latest Guacamole tag
      # Format: 'Major.minor.rev(-RCcandidate)?'
      - name: Get Latest Guacamole Tag
        id: latest_tag
        uses: oraad/get-tags-action@v1.0.0
        with:
          repo: apache/guacamole-client
          limit: 1
      
      # Check the tag we got back
      - name: Check Output
        run: |
          echo "Latest Tag - ${{ steps.latest_tag.outputs.tags }}"
      
      # Get our latest release
      # Format: 'vMajor.minor.rev'
      - name: Get Latest Local Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}
      
      # If the latest Guacamole tag doesn't match our latest release, and also doesn't end in '-RCx',
      # Create a new release for the Guacamole tag
      - name: Create Release 
        if: ${{ steps.latest_release.outputs.release }} != ${{ steps.latest_tag.outputs.tags }}
        run: | 
          echo "Creating release v${{ steps.latest_tag.outputs.tags }}"
        
