# This is a basic workflow to help you get started with Actions

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-latest-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Docker Hub Tag
        # You may pin to the exact commit or the version.
        # uses: jacobtomlinson/gha-get-docker-hub-tags@4d1339c986f06d2b6ffc2ef0fff024dca0ef0735
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
        with:
          # The Docker Hub org
          org: guacamole
          # The Docker Hub repo
          repo: guacamole
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
