# This is a basic workflow to help you get started with Actions

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      # Get the latest Guacamole Docker tag
      - name: Get Docker Hub Tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
        with:
          # The Docker Hub org
          org: 'guacamole'
          # The Docker Hub repo
          repo: 'guacamole'
          
      # Use the tag we got back
      - name: Check outputs
        run: |
          echo "Latest Image Tag - ${{ steps.latest_tag.outputs.tag }}"
