# This is a basic workflow to help you get started with Actions

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-latest-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Latest Release Tag
        # You may pin to the exact commit or the version.
        # uses: ctrlaltdev/latest-release-json-action@cdd9e774cdf4ef4f2c4caa4581236c31e1f43249
        uses: ctrlaltdev/latest-release-json-action@v1.0.1
        with:
          # JSON of GitHub Releases
          releases: 'apache/guacamole-client'
          # If you want the version to be prefixed with `v`
          prefixed: true # default is false
