# This is a basic workflow to help you get started with Actions

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-latest-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Release
        # You may pin to the exact commit or the version.
        # uses: joutvhu/get-release@892bd55b92fd5a79f97836964d6abc7b81bb1bdd
        uses: joutvhu/get-release@v1.0.1
        with:
          # The name of the owner of the repo. Used to identify the owner of the repository.
          owner: apache
          # The name of the repository. Used to identify the repository on which to release.
          repo: guacamole-client
          # Should get latest release?
          latest: false
          # Show ouputs
          debug: true
          # Fail when no release was found
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
