# Checks for new upstream releases and creates matching local releases

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      # Get the latest Guacamole tag
      # Format: 'Major.minor.rev(-RCcandidate)?'
      - name: Get Latest Guacamole Tag
        id: latest_tag
        uses: oraad/get-tags-action@v1.0.0
        with:
          repo: apache/guacamole-client
          limit: 1
      
      # Check the Guacamole tag we got back
      - name: Check Output
        run: |
          echo "Latest Guacamole - ${{ fromJSON(steps.latest_tag.outputs.tags)[0] }}"
      
      # Get our latest release
      # Format: 'vMajor.minor.rev'
      - name: Get Latest Local Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}
          
      # Check the local release we got back
      - name: Check Output
        run: |
          echo "Latest Local - ${{ steps.latest_release.outputs.release }}"
          
      # If the latest Guacamole tag doesn't match our latest release,
      - name: Compare Versions
        id: compare_versions
        if: ${{ !contains('-', fromJSON(steps.latest_tag.outputs.tags)[0]) && !endsWith(steps.latest_release.outputs.release, fromJSON(steps.latest_tag.outputs.tags)[0]) }}
        run: |
          echo "Creating release ${{ format('v{0}',fromJSON(steps.latest_tag.outputs.tags)[0]) }}"
      
      # Checkout the code for a commit
      #- name: Checkout
      #  if: ${{ !contains('-', fromJSON(steps.latest_tag.outputs.tags)[0]) && !endsWith(steps.latest_release.outputs.release, fromJSON(steps.latest_tag.outputs.tags)[0]) }}
      #  uses: actions/checkout@v2
        
      # Create a commit for this release
      #- name: Commit
      #  id: commit
      #  if: ${{ !contains('-', fromJSON(steps.latest_tag.outputs.tags)[0]) && !endsWith(steps.latest_release.outputs.release, fromJSON(steps.latest_tag.outputs.tags)[0]) }}
      #  uses: zwaldowski/git-commit-action@v1
      #  with:
      #    commit_message: Bumping version to ${{ format('v{0}',fromJSON(steps.latest_tag.outputs.tags)[0]) }}
      
      # Create a new release for the Guacamole tag
      - name: Create Release
        if: ${{ !contains('-', fromJSON(steps.latest_tag.outputs.tags)[0]) && !endsWith(steps.latest_release.outputs.release, fromJSON(steps.latest_tag.outputs.tags)[0]) }}
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ format('v{0}',fromJSON(steps.latest_tag.outputs.tags)[0]) }}
          commit: main
