# This is a basic workflow to help you get started with Actions

name: Check Upstream Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      # Get the latest Guacamole Docker tag
      #- name: Get Docker Hub Tag
      #  uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.3
      #  with:
      #    # The Docker Hub org
      #    org: 'guacamole'
      #    # The Docker Hub repo
      #    repo: 'guacamole'
      
      - name: Get Latest Tag
        id: latest_tag
        uses: oraad/get-tags-action@v1
        with:
          repo: apache/guacamole-client
          limit: 1
      
      # Use the tag we got back
      - name: Check outputs
        run: |
          echo "Latest Tag - ${{ steps.latest_tag.outputs.tags }}"
